name: football_fans_tv
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  flutter_countdown_timer: ^4.1.0
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3
  get: ^4.6.1
  http: ^0.13.4
  intl: ^0.17.0
  invert_colors: ^0.0.4
  marquee: ^2.2.1
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.7
  package_info_plus: ^3.0.1
  url_launcher: ^6.0.20
  hexcolor: ^3.0.1
  page_transition: ^2.0.2
  webview_flutter: ^3.0.4
  wakelock: ^0.6.1+2
  onesignal_flutter: ^3.3.0
  share_plus: ^6.0.1
  google_fonts: ^3.0.1
  nimu_shimmer: ^0.0.1
  shimmer: ^2.0.0
  flutter_inappwebview: ^5.4.3+7
  youtube_player_iframe: ^3.1.0
  photo_view: ^0.14.0
  loader_overlay: ^2.0.7
  load: ^1.0.0
  font_awesome_flutter: ^10.2.1
  toggle_switch: ^2.0.1
  intl_phone_number_input: ^0.7.0+2
  otp_text_field: ^1.1.3
  pinput: ^2.2.11
  country_codes: ^2.2.0
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.10.0
  animated_widgets: ^1.1.0
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  md2_tab_indicator: ^1.0.2
  fluid_bottom_nav_bar:
    path: packages/fluid-nav-bar
  better_player: ^0.0.80
  morphable_shape: ^1.6.4
  google_sign_in: ^5.4.1
  device_info_plus: ^7.0.1
  video_player: ^2.4.7
  visibility_detector: ^0.2.2
  sign_in_with_apple: ^4.1.0
  flutter_inapp_purchase: ^5.3.1
  google_mobile_ads: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/applogo.png"
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Black.ttf
        - asset: assets/fonts/Barlow-Bold.ttf
        - asset: assets/fonts/Barlow-ExtraBold.ttf
        - asset: assets/fonts/Barlow-ExtraLight.ttf
        - asset: assets/fonts/Barlow-Medium.ttf
        - asset: assets/fonts/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow-SemiBold.ttf
        - asset: assets/fonts/Barlow-Thin.ttf
        - asset: assets/fonts/Barlow-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
